### ISSUE TITLE
Dominion Randomizer only using base set cards (all of a sudden)

### ISSUE THREAD

**Issue by theshampooguy** [blakevanlan/KingdomCreator#58] opened 2020-08-16 06:09 UTC
Please advise...

**Comment by theshampooguy** [comment] 2020-08-18 05:44
![image](https://user-images.githubusercontent.com/69745535/90474843-10a61180-e0db-11ea-93b8-6bf8a49fe9dc.png)

![image](https://user-images.githubusercontent.com/69745535/90474880-274c6880-e0db-11ea-9abe-ccd0ff5c6c19.png)

**Comment by davidtorosyan** [comment] 2020-09-20 02:45
Hey @theshampooguy, this is actually an issue in my plugin [command.games](https://github.com/davidtorosyan/command.games). I tracked down the issue myself just now, and it has to do with a recent change in how Chrome handles cookies.

@blakevanlan, my plugin doesn't work anymore in Chrome because of [SameSite cookies](https://web.dev/samesite-cookies-explained/). Basically, my strategy of "open dominion.games in an iFrame to use the data there" is considered a privacy breach. Which... yeah, that sounds about right.

The fix is to set the `options` cookie with `SameSite=None` so I can load it properly. Any thoughts on this? I can try drafting a PR.

**Comment by theshampooguy** [comment] 2020-09-20 06:29
Sounds good.

It's still not working.

Thanks.

**Comment by blakevanlan** [comment] 2020-09-20 15:08
@theshampooguy - Just merged PR #63 which should allow command.games to work again.

**Closed by blakevanlan** 2020-09-20 15:08 UTC

**Comment by davidtorosyan** [comment] 2020-09-20 17:22
Thanks @blakevanlan!

**Comment by theshampooguy** [comment] 2020-09-21 18:45
I've reloaded the extension, but it still doesn't work on Chrome.

I tried it on Edge, and it does work.


Thanks

**Comment by davidtorosyan** [comment] 2020-09-21 18:48
@theshampooguy weird, it's working for me on Chrome. Can you verify the version of command.games you're using? It might also help to reopen the issue on [my repo](https://github.com/davidtorosyan/command.games) since the issue is specific to the plugin.

**Comment by theshampooguy** [comment] 2020-09-21 18:53
It looks like v 1.5.0?

[image: image.png]

**Comment by davidtorosyan** [comment] 2020-09-21 18:55
@theshampooguy can you try reconfiguring your choices in dominionrandomizer? I think maybe the cookie needs to be reissued.

**Comment by theshampooguy** [comment] 2020-09-21 19:45
I had done that several times over the past few days.

But I did it again, and it worked--thanks!
