### ISSUE TITLE
Add card translations

### ISSUE THREAD

**Issue by wdeweijer** [blakevanlan/KingdomCreator#26] opened 2020-02-10 22:47 UTC
Since I have a Dutch version of Dominion it's a bit of a nuisance to select the deck from the box (having to guess the correct translation or look for artwork). So it would be very nice if there was an option to include the card translations in some of the other languages the game is published in.

I've included a csv with all the translations for Dutch and German (the only two complete ones I could find) that I got from the dominionstrategy wiki ([here](http://wiki.dominionstrategy.com/index.php?title=List_of_cards_in_other_languages)). There are some promo cards that never got a Dutch release so I left them Null. There are also some German cards that have different names in different releases (Soothsayer and Walled Village) so I picked the translation from most recent release.

[dominion_translations_csv.txt](https://github.com/blakevanlan/KingdomCreator/files/4183406/dominion_translations_csv.txt) (it's in the shape English, Dutch, German)

**Comment by blakevanlan** [comment] 2020-02-10 23:20
Hi @wdeweijer,

Thanks for the lists! I'll work on integrating translations for all the cards. 

Would you be interested in translating other pieces of the site such as the checkbox labels?

**Comment by wdeweijer** [comment] 2020-02-11 15:21
Sure! But I don't know much about web dev and have never done localization before so I'm not quite sure where to start. If all the text you would like translated was extracted to a separate file (or however you want to organize it) I would gladly provide translations (at least for Dutch).

**Comment by blakevanlan** [comment] 2020-02-15 18:46
No problem! I'll give you a list of phrases that need to be translated with some indication of where those phrases appear. 

Working on building the infrastructure for handling translations this weekend.

**Comment by blakevanlan** [comment] 2020-02-23 05:16
@wdeweijer Dutch and German card translations are live! 

I'm still working on getting the rest of the site translated but if you're still interested I can provide you a spreadsheet with the phrases to translate. Just let me know!

**Comment by wdeweijer** [comment] 2020-02-24 13:12
It looks great! The card translations work really well. I'd be happy to translate more of the site.

A few mistakes I spotted:
- In the language menu: "German" as a noun in Dutch is "Duits" and in German "Deutsch"
- promos_walledvillage is still called "Null" in Dutch. Since this card doesn't exist it might be best to leave it blank or to make up a name. "Ommuurd Dorp" would work.
- A bit unfortunate but "Dark Ages" is "De Donkere Middeleeuwen" in Dutch (not "De Donkere" as it is now) which doesn't fit on one line. It would be best to either live with the linebreak or change it to "Middeleeuwen" which is not the official name but is unambiguous.

**Comment by blakevanlan** [comment] 2020-02-25 02:03
Thanks for the thoroughness here!

I fixed all of the issues you pointed out. Couple notes:
- For promos_walledvillage, went with "Ommuurd Dorp"
- "De Donkere Middeleeuwen" is unfortunately long.. went with your suggestion ("Middeleeuwen")

I continued pulling more of the site's language into message files but didn't get a chance to finish yet. Once I get them all pulled into message files I can give you a dump.

If you're really interested you can just submit a pull request against the [message files](https://github.com/blakevanlan/KingdomCreator/tree/master/src/i18n/messages): 
- `page-index.{de|nl}.json`
- `page-sets.{de|nl}.json`
- `page-rules.{de|nl}.json`
- `common.{de|nl}.json` - Not sure it's worth really translating the disclosures but up to you

Thanks for all the help! 😄

**Comment by gillesgros** [comment] 2020-03-02 18:08
Hello, 

For French cards translation, I am working on providing you all the jpg card files.
My 2 cents : I do not feel it is needed to translate all the pages


regards

**Comment by blakevanlan** [comment] 2020-03-11 01:17
Sounds great @gillesgros! I'll provide a spreadsheet (eventually) with some of the site phrases if you do end up wanting to help translate portions of the UI that aren't just the cards.

**Comment by gillesgros** [comment] 2020-03-11 15:16
Not problem for helping on translation..
Here are some translated files

[messages-fr.zip](https://github.com/blakevanlan/KingdomCreator/files/4319039/messages-fr.zip)

**Comment by blakevanlan** [comment] 2020-03-21 16:19
The French cards have been added (deployed in #46).

There are a few cards that I temporarily used the English version for until we can find a French version:
- Encampment / Plunder (combined card)
- Settler / Bustling Village (combined card)
- Catapult / Rocks (combined card)
- Patrician / Emporium (combined card)
- Gladiator / Fortune (combined card)
- Stash

**Comment by gillesgros** [comment] 2020-03-21 17:05
I have made those cards.
i will send them to you tomorrow

Gilles

**Comment by gillesgros** [comment] 2020-03-22 10:53
Hello,

here are the cards that were missing.
I realized that the card package I made was broken (all cards named
with seaside). Sorry for that.

Regards

suggestions :
1- I would suggest to place cards in extension set folder, so that it might
be easier to find if needed.
2- I will try to do the same as cards for Boxes and rules that exist in
other languages (french for my part).
2 - I will soon provide you and update of kingdoms, I noticed some glitches.
3- to simplify the set files, you should ass for events, landmarks and
projects a piece of code that handle the fact that you set no cost.
Example for projects

===================================
import {Addon} from "./addon"
import {Cost} from "./cost"
import {SetId} from "./set-id"

export class Project implements Addon {
  constructor(
    readonly id: string,
    readonly shortId: string,
    readonly setId: SetId,
    readonly name: string,
    readonly cost: Cost) {
  }

  public static fromJson(json: any) {
   if ( typeof json["cost"] === 'undefined' ) {
     return new Project(
        json["id"],
        json["shortId"],
        json["setId"],
        json["name"]
        new Cost(0,0,0));
   }

    return new Project(
      json["id"],
      json["shortId"],
      json["setId"],
      json["name"]
      Cost.fromJson(json["cost"]));
  }
}

**Comment by blakevanlan** [comment] 2020-03-28 14:01
Hey @gillesgros,

Thanks for the suggestions. The cards you mention don't seem to be attached.

I agree that separating out the languages makes sense. I ended up with this structure: `/docs/img/cards/fr/...`.

Left the English cards in the same place for now but may move them later.

I didn't totally follow what you were talk about for the cost since the cost is being defined in the set yaml files for all events, projects and landmarks.

**Comment by gillesgros** [comment] 2020-03-29 07:48
Hi Blake,

**1 - Missing cards**
I attached the cards again (before reply by email. I suppose it removes attachments.
[_For Blake missing cards.zip](https://github.com/blakevanlan/KingdomCreator/files/4398419/_For.Blake.missing.cards.zip)

**2 - Image folder structure**
I agree with the structure modification for language.
On my side, I store image file by set (adventures, seaside, baseset, ...).
So there is less files in 1 folder.
On This one, it is for you to decide.

**3 - Events, landmarks, project set simplification**
to simplify the set files, for projects and landmark
if you add the piece of code in my previous message, the empires.yaml file can be simplified for landmarks.

===============
landmarks:
  - name: Aqueduct
  - name: Arena
  - name: Bandit Fort
  - name: Basilica
  - name: Baths
  - name: Battlefield
  - name: Colonnade
  - name: Defiled Shrine
  - name: Fountain
  - name: Keep
  - name: Labyrinth
  - name: Mountain Pass
  - name: Museum
  - name: Obelisk
  - name: Orchard
  - name: Palace
  - name: Tomb
  - name: Tower
  - name: Triumphal Arch
  - name: Wall
  - name: Wolf Den
============================
This might also be useful  when setting "Menagerie" set 

**4 - multiple reload related to language**
I was reproducing my changes on the new structure of your code. I noticed that when I set language to french, there are multiple loading request that make the page switch from encglish and then to french.
I tried to understand how to fx it, but I did not figure it out. If you have a clue.

Regards

**Comment by gillesgros** [comment] 2020-03-30 10:48
Hello Blake,

Hope you're fine during this troubled period.
I updated my version in relation to your new code structure.
Have a look a [71yeti.fr](https://71yeti.fr)

Regards

**Comment by blakevanlan** [comment] 2020-04-04 23:46
@gillesgros & @wdeweijer - I've added Menagerie support in English. Feel free to propose pull requests for the other languages!

**Comment by davidtorosyan** [comment] 2020-09-20 04:31
I think the Copy button still copies in English. Has it been updated to support translations?

**Comment by blakevanlan** [comment] 2020-09-20 15:42
Just merged #65 to fix this and also include all the addons (events, projects, etc) when copying.

**Comment by davidtorosyan** [comment] 2020-09-20 17:42
More fun edge cases. I was testing copy/paste in German, and found that some cards didn't make it over.

| English      | dominionrandomizer.com | dominion.games |
| ------------ | ---------------------- | -------------- |
| Grand Market | Grosser Markt          | Großer Markt   |
| Citadel      | Zitdelle               | Zitadelle      |

I'm sure there are more. If you search through [the source](https://dominion.games/js/dominion-webclient-body-1.5.3.5.min.js) (for, say, `Zitadelle`), you can find the translations that they went with.

**Comment by blakevanlan** [comment] 2020-09-20 18:04
Bummer! At least it should be pretty straightforward to extract via a script.

**Comment by Soketin** [comment] 2021-01-27 09:21
Hello there! I would love to add Spanish language to the web. Could you please send me the files or file to translate? Thank you very much!!! :)

**Comment by gillesgros** [comment] 2023-05-04 08:08
translation updated

**Closed by gillesgros** 2023-05-04 08:08 UTC
